config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :tasks
  resources :labels

  #session
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  #user
  
  namespace :admin do
    resources :users , only: [:create, :show, :edit, :update, :destroy]
    get 'sign_up', to: 'users#new'
    root 'users#index'
  end
  

  root 'tasks#index'


  match '/404', to: "errors#not_found", via: :all
  match '/500', to: "errors#internal_server_error", via: :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/label.rb
class Label < ApplicationRecord
    has_many :label_relations
    has_many :tasks, through: :label_relations
    validates :name ,presence: true
end

app/models/label_relation.rb
class LabelRelation < ApplicationRecord
    belongs_to :task
    belongs_to :label
end

app/models/task.rb
class Task < ApplicationRecord
    include AASM

    aasm column: :status do 
        state :pending  , initial: true
        state :process , :finish
    
    event :do_it do
        transitions from: :pending, to: :process
    end

    event :finish_it do
        transitions from: :process, to: :finish
    end
    end
    belongs_to :user
    validates :start_time, :end_time, :title, :status, :order ,presence: true
    validate :time_order ,if: :time_present?

    has_many :label_relations
    has_many :labels, through: :label_relations

    # 可以用 Post.tagge_with(tagname) 來找到文章
    def self.labelled_with(name)
        Label.find_by!(name: name).posts
    end
        
    # # tag_list 的 setter
    # def tag_list=(names)
    #     self.tags = names.split(',').map do |item|
    #       Tag.where(name: item.strip).first_or_create!
    #     end
    #   end
    
    def label_items
        labels.map(&:name).join(', ')
    end

    def label_items=(names)
        self.labels = names.map{|item|
            Label.where(name: item.strip).first_or_create! unless item.blank?}.compact!
    end

    private
    def time_present?
        start_time.presence && end_time.presence
    end
    def time_order 
        if end_time < start_time
            errors.add :end_time, 'Cannot earlier than start time!'
        end
    end

end

app/models/user.rb
class User < ApplicationRecord
    has_many :tasks, :dependent => :delete_all
    validates :user_name, :email, :password ,presence: true
    has_secure_password

      # Admin deletion settings
    scope :is_admin, -> { where(admin: true)}
    
    before_save :check_admin_count
    def check_admin_count
        if self.admin_changed?(from: true, to: false) && User.is_admin.count == 1
            errors.add :admin, message: I18n.t('notice.no_admin')
            throw :abort
        end
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

    before_action :find_user, except: %i[new create]
    before_action :require_admin

    def index 
        @users = User.order(id: :ASC).page(params[:page]).per(9)
    end

    def new
        @user = User.new
    end
    
    def show
        
        @q = @user.tasks.ransack(params[:q])
        @tasks = @q.result.order('id ASC').page(params[:page]).per(9)

    end

    def create
        @user = User.new(user_params)
        if @user.save
            redirect_to admin_root_path , notice: t('notice.new')
        else 
            render :new
        end
    end

    def edit 
    end
    
    def destroy
        @user.destroy
        redirect_to admin_root_path, notice: I18n.t('notice.delete')
    end

    def update
        
        if @user.update(admin_params)
            redirect_to admin_root_path
            flash[:notice] = I18n.t('notice.update')
        else
            flash[:notice] = @user.errors.full_messages.to_sentence
            render :edit
        end

    end

    private
    def find_user 
        @user = User.find_by(id: params[:id])
    end

    def user_params
        params.require(:user).permit(:user_name, :email, :password)
    end

    def admin_params
        params.require(:user).permit(:user_name, :email, :password, :admin)
    end

    def require_admin
        return if current_user&.admin == true
        
        flash[:notice] = I18n.t('notice.not_admin')
        redirect_to root_path 
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?
    
    def log_in(user)
        session[:user_id] = user.id
    end
    def current_user
      @current_user ||= User.find_by(id: session[:user_id])
    end
    def logged_in?
      !current_user.nil?
    end

  
       
    def logged_in_user
      unless logged_in?
        flash[:notice] = t('notice.not_login')
        redirect_to login_path
      end
    end
 
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController

    def not_found
        render :not_found
    end

    def internal_server_error
        render :internal_server_error
    end
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
    def index
        @labels = Label.page(params[:page]).per(9)
    end
    def new
        @label = Label.new
    end
    def create
        @label= Label.new(label_params)

        if @label.save
            flash[:notice] = I18n.t('notice.new')
            redirect_to labels_path
            
        else
            flash[:notice] = @label.errors.full_messages.to_sentence
            render :new
        end
    end

    def destroy
        Label.find_by(id: params[:id]).destroy
        redirect_to labels_path, notice: I18n.t('notice.delete')
    end

    private

    def label_params
        params.require(:label).permit(:name)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action :find_session_user , only: %i[create delete]

  def new
  end
# 使用者登入
  def create
    if @user && @user.authenticate(params[:session][:password])
      log_in(@user)
      flash[:notice] = I18n.t('notice.login')
      if !current_user.admin?
        redirect_to tasks_path(@user)
      else
        redirect_to admin_root_path
      end
    else
      redirect_to login_path, notice: I18n.t('notice.login_fail')

    end
  end
# 使用者登出
  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: I18n.t('notice.logout')
  end

  private

  def find_session_user
    @user = User.find_by(email: params[:session][:email].downcase)
  end
  

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :logged_in_user, only: [:index, :new, :create, :edit, :update, :destroy]

    def index

        @q = current_user.tasks.ransack(params[:q])
        @tasks = @q.result
        @tasks = @tasks.order(id: :ASC).page(params[:page]).per(9)

    end

    def new
        @task = Task.new
    end

    def create
        @task = current_user.tasks.new(task_params)


        if @task.save
            flash[:notice] = I18n.t('notice.new')
            redirect_to tasks_path
            
        else
            flash[:notice] = @task.errors.full_messages.to_sentence
            render :new
        end
    end
    def edit
        @task = Task.find_by(id: params[:id])
    end
    
    def destroy
        @task = Task.find_by(id: params[:id])
        @task.destroy if @task
        redirect_to tasks_path, notice: I18n.t('notice.delete')
    end

    def update
        @task = Task.find_by(id: params[:id])
        if @task.update(task_params)
            redirect_to tasks_path
            flash[:notice] = I18n.t('notice.update')
        else
            flash[:notice] = @task.errors.full_messages.to_sentence
            render :edit
        end
    end
    private
    def task_params
        params.require(:task).permit(:title,:start_time,:end_time,
                                    :status,:content,:order,{ label_items: [] } )
    end    


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form_user.html.erb
<h3> <%= @error_messgae%></h3>

<%= simple_form_for user , url: admin_users_path do |form| %>
    <%# <div class = 'wrap'> %>
    <%= form.input :user_name %>
    <%= form.input :email %>
    <%= form.input :password %>
    <%= form.submit%>
    <%# </div> %>
<%end%>

app/views/admin/users/_task_by_user.html.erb
<h1> <%= t("page_name.index_page")%></h1>

<%= search_form_for @q do |f| %>
  <%= f.label :title_cont ,t('search_form.title')%>
  <%= f.search_field :title_cont %>
  <br>

  <%= f.label :status_eq ,t('search_form.status')%>
  <%= f.radio_button :status_eq, '' %>
  <%= f.label t('search_form.all') %>
  <%= f.radio_button :status_eq, 'pending' %>
  <%= f.label t('types.status.pending') %>
  <%= f.radio_button :status_eq, 'process' %>
  <%= f.label t('types.status.process') %>
  <%= f.radio_button :status_eq, 'finish' %>
  <%= f.label t('types.status.finish') %>
  <br>
<%= f.submit %>
<% end %>
<br>
<table class = "table" id="task_table">
  <thead>
    <tr>
      <td><%=@tasks.human_attribute_name(:title) %></td>
      <td><%=sort_link(@q, :created_at ,@tasks.human_attribute_name(:created_at) ,default_order: :desc) %></td>
      <td><%=@tasks.human_attribute_name(:start_time)%></td>
      <td><%=sort_link(@q, :end_time , @tasks.human_attribute_name(:end_time) ,default_order: :desc) %></td>
      <td><%=@tasks.human_attribute_name(:status)%></td>
      <td><%=@tasks.human_attribute_name(:content)%></td>
      <td><%=sort_link(@q, :order , @tasks.human_attribute_name(:order) ,default_order: :desc)%></td>
      <td><%=@tasks.human_attribute_name(:category)%></td>

    </tr>

  </thead>

  <tbody>
  <% @tasks.each do |task| %>
  <tr>
    <td><%= task.title %></td>
    <td><%= task.created_at.strftime("%Y/%m/%d")  %></td>
    <td><%= task.start_time.strftime("%Y/%m/%d")  %></td>
    <td><%= task.end_time.strftime("%Y/%m/%d")  %></td>
    <td><%= t("types.status.#{task.status}")%></td>
    <td><%= task.content%></td>
    <td><%= t('types.order')[task.order] %></td>
    <td><%= task.label_items() %></td>
   

  </tr>
  <% end %>
</tbody>
</table>
<%= paginate @tasks%> 
<br>

app/views/admin/users/edit.html.erb
<h3><%= t('page_name.user_edit_page')%></h3>
<h3> <%= @error_messgae%></h3>

<%= simple_form_for @user , url: "/admin/users/#{@user.id}"  do |form| %>
 
    <%= form.input :user_name %>
    <%= form.input :email %>
    <%= form.input :password %>
    <% if current_user.admin? %>
      <%= form.input :admin ,as: :radio_buttons , 
      collection:[[t('types.admin.add'),true],[t('types.admin.minus'),false]]%>
    <% end %>
    
    <%= form.submit %>

<%end%>
<br>
<%= link_to t('back.admin'), admin_root_path %>

app/views/admin/users/index.html.erb
<h1> <%= t("page_name.user_index_page")%></h1>

<br>
<table class = "table" id="task_table">
  <thead>
    <tr>
      <td><%= @users.human_attribute_name(:user_name) %></td>
      <td><%= @users.human_attribute_name(:email)%></td>
      <td><%= t('tasks_num')%></td>

    </tr>

  </thead>

  <tbody>
  <% @users.each do |user| %>
  <tr>
    <td><%= link_to user.user_name , admin_user_path(user)%></td>
    <td><%= user.email  %></td>
    <td><%= user.tasks.count%></td>
    
    <td>
        <%= link_to t("action.edit") , edit_admin_user_path(user) %>
        <%= link_to t('action.delete'), admin_user_path(user), method: "delete", 
        data: { confirm: t('action.delete_confirm') } ,id:"delete-#{user.id}"%>
    </td>

  </tr>
  <% end %>
</tbody>
</table>
<%= paginate @users %> 
<br>

<%= link_to t('action.new_user'), admin_sign_up_path %>
<br><br>
<%= link_to t('action.logout'), sessions_destroy_path%>

app/views/admin/users/new.html.erb
<h1><%= t('page_name.new_user_page')%></h1>

<%= render 'form_user' ,user: @user ,error_messgae: @error_messgae %>

app/views/admin/users/show.html.erb
<%= render 'task_by_user' , tasks: @tasks%>

<%= link_to t('back.admin'), admin_root_path %><br><br>
<% if current_user == @user %>
  <%= link_to '去自己的任務頁面', tasks_path %>
<% end %>

app/views/labels/_form.html.erb
<%= simple_form_for(label) do |f| %>
  <%= f.input :name %>
  
  <%= f.submit %>
<% end %>

app/views/labels/index.html.erb
<h1> <%= t("page_name.label_page")%></h1>


<table class = "table" id="label_table">
  <thead>
    <tr>
      <td><%=@labels.human_attribute_name(:name) %></td>
      
    </tr>

  </thead>

  <tbody>
  <% @labels.each do |label| %>
  <tr>
    <td><%= label.name %></td>
    <td>
        <%= link_to t('action.delete'), label_path(label), method: "delete", 
        data: { confirm: t('action.delete_confirm') } ,id:"delete-#{label.id}"%>
    </td>

  </tr>
  <% end %>
</tbody>
</table>
<%= paginate @labels%> 
<br>

<%= link_to t('action.new_label'), new_label_path %>
<br><br>
<%= link_to t('back.task'), tasks_path %>

app/views/labels/new.html.erb
<h1><%= t('page_name.new_label_page')%></h1>



<%= render 'form' , :label => @label %>

<br />
<%= link_to t('back.label'), labels_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Todo list</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class = 'container'>
    <p style="color: green"><%= flash[:notice] %></p>
    <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= simple_form_for(task) do |f| %>
  <%= f.input :title %>
  <%= f.input :start_time , wrapper: :horizontal_select_date %>
  <%= f.input :end_time , wrapper: :horizontal_select_date%>
  <%= f.input :status  ,as: :radio_buttons ,
        collection:[:pending, :process, :finish] ,
        :item_wrapper_class => 'radio-inline'%>

  <%= f.input :content %>

  <%= f.input :order ,as: :radio_buttons ,
        collection:[[t('types.order')[0],0], [t('types.order')[1],1], [t('types.order')[2],2]] ,
        :item_wrapper_class => 'radio-inline'%>
        
  <%= f.input :label_items, as: :select, collection: Label.order(:name), label_method: :name,value_method: :name, input_html: {multiple: true} %>

  <%= f.submit %>
<% end %>

app/views/tasks/_prevent_login.html.erb
  <h2>
  Please Log in to Manage Your Tasks
  </h2>


<%= link_to '登入', login_path %>

app/views/tasks/_tasklist.html.erb
<h1> <%= t("page_name.index_page")%></h1>

<%= search_form_for @q do |f| %>
  <%= f.label :title_cont ,t('search_form.title')%>
  <%= f.search_field :title_cont %>
  <br><br>

  <%= f.label :status_eq ,t('search_form.status')%>
  <%= f.radio_button :status_eq, '' %>
  <%= f.label t('search_form.all') %>
  <%= f.radio_button :status_eq, 'pending' %>
  <%= f.label t('types.status.pending') %>
  <%= f.radio_button :status_eq, 'process' %>
  <%= f.label t('types.status.process') %>
  <%= f.radio_button :status_eq, 'finish' %>
  <%= f.label t('types.status.finish') %>
  <br><br>
  <%= f.label t('search_form.label')%>
  <% Label.all.each do |s| %>
    <%= radio_button_tag('q[labels_id_eq_any][]' , s.id) %>
    <%= s.name%>  
  <% end %>
  <br><br>
  <%= f.submit %>
<% end %>
<br>
<table class = "table" id="task_table">
  <thead>
    <tr>
      <td><%=@tasks.human_attribute_name(:title) %></td>
      <td><%=sort_link(@q, :created_at ,@tasks.human_attribute_name(:created_at) ,default_order: :desc) %></td>
      <td><%=@tasks.human_attribute_name(:start_time)%></td>
      <td><%=sort_link(@q, :end_time , @tasks.human_attribute_name(:end_time) ,default_order: :desc) %></td>
      <td><%=@tasks.human_attribute_name(:status)%></td>
      <td><%=@tasks.human_attribute_name(:content)%></td>
      <td><%=sort_link(@q, :order , @tasks.human_attribute_name(:order) ,default_order: :desc)%></td>
      <td><%=@tasks.human_attribute_name(:category)%></td>

    </tr>

  </thead>

  <tbody>
  <% @tasks.each do |task| %>
  <tr>
    <td><%= task.title %></td>
    <td><%= task.created_at.strftime("%Y/%m/%d")  %></td>
    <td><%= task.start_time.strftime("%Y/%m/%d")  %></td>
    <td><%= task.end_time.strftime("%Y/%m/%d")  %></td>
    <td><%= t("types.status.#{task.status}")%></td>
    <td><%= task.content%></td>
    <td><%= t('types.order')[task.order] %></td>
    <td><%= task.label_items() %></td>
    <td>
        <%= link_to t("action.edit") , edit_task_path(task) %>
        <%= link_to t('action.delete'), task_path(task), method: "delete", 
        data: { confirm: t('action.delete_confirm') } ,id:"delete-#{task.id}"%>
    </td>

  </tr>
  <% end %>
</tbody>
</table>
<%= paginate @tasks%> 
<br>

app/views/tasks/edit.html.erb
<h1><%=t('page_name.edit_page')%></h1>

<%= render "form", :task => @task %>

<br>
<%= link_to t('back.task'), tasks_path %>

app/views/tasks/index.html.erb
<%= render "tasklist", tasks: @tasks %>

<%= link_to t('action.new'), new_task_path %>

<% if current_user.admin? %>
  <br><br><%= link_to t('page_name.user_index_page'), admin_root_path %>
<% end %><br><br>

<%= link_to t('page_name.label_page'), labels_path %>
<br><br>
<%= link_to t('action.logout'), sessions_destroy_path%>

app/views/tasks/new.html.erb
<h1><%= t('page_name.new_page')%></h1>



<%= render 'form' , :task => @task %>

<br />
<%= link_to t('back.task'), tasks_path %>

app/views/users/edit.html.erb
<h3><%= t('page_name.user_edit_page')%></h3>
<h3> <%= @error_messgae%></h3>

<%= simple_form_for(@user) do |form| %>
 
    <%= form.input :user_name %>
    <%= form.input :email %>
    <%= form.input :password %>
    <%= form.submit%>

<%end%>
<br>
<%= link_to t('back.admin'), admin_path %>

app/views/users/index.html.erb
<h1> <%= t("page_name.user_index_page")%></h1>

<br>
<table class = "table" id="task_table">
  <thead>
    <tr>
      <td><%= @users.human_attribute_name(:user_name) %></td>
      <td><%= @users.human_attribute_name(:email)%></td>
      <td><%= t('tasks_num')%></td>

    </tr>

  </thead>

  <tbody>
  <% @users.each do |user| %>
  <tr>
    <td><%= link_to user.user_name , user%></td>
    <td><%= user.email  %></td>
    <td><%= user.tasks.count%></td>
    
    <td>
        <%= link_to t("action.edit") , edit_user_path(user) %>
        <%= link_to t('action.delete'), user_path(user), method: "delete", 
        data: { confirm: t('action.delete_confirm') } ,id:"delete-#{user.id}"%>
    </td>

  </tr>
  <% end %>
</tbody>
</table>
<%= paginate @users %> 
<br>

<%= link_to t('action.new_user'), new_user_path %>